### PR TITLE
Remove cookie vvv env and default to `build`

### PR DESCRIPTION
**Pull request by tomjn**

### CODE REVIEW

**Comment by tomjn** [comment]
Not sure what can be done about WP CLI since it's already been changed from `public_html/src` to `public_html/build` as expected.

**Comment by tomjn** [comment]
With the latest commits it works here

**Comment by spacedmonkey** [comment]
I tested this last night and my development envoriment provision correctly again. I do have to use grunt watch now to use development env, which is a pain to remember to do this. 

However I can confirm it works and the change seems sound (in the little I have looked at it) to me. :+1:

**Comment by iceablemedia** [comment]
This seems to work for me too on a brand new VVV install.
Just like spacedmonkey in the above comment, I haven't spent much time yet looking into details yet.

**Pull request merged**
